# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'SLINK' do
  use_frameworks!
  
  # Pods for SLINK
  pod 'AWSDynamoDB', '~> 2.6.13'
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSUserPoolsSignIn', '~> 2.6.13'
  pod 'AWSAuthUI', '~> 2.6.13'
  pod 'Charts'
  #pod 'AWSIoT'
  pod 'CocoaMQTT'

  target 'SLINKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SLINKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
