//
//  DATA.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class DATA: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _uName: String?
    var _timePlusNum: String?
    var _wODName: String?
    var _exName: String?
    var _forceList: [String]?
    var _reps: String?
    var _speedList: [String]?
    var _timestampFirst: String?
    var _timestampLast: String?
    var _weight: String?
    
    class func dynamoDBTableName() -> String {

        return "slink-mobilehub-286091421-DATA"
    }
    
    class func hashKeyAttribute() -> String {

        return "_uName"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_timePlusNum"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_uName" : "u_name",
               "_timePlusNum" : "time_plus_num",
               "_wODName" : "WOD_name",
               "_exName" : "ex_name",
               "_forceList" : "forceList",
               "_reps" : "reps",
               "_speedList" : "speedList",
               "_timestampFirst" : "timestamp_first",
               "_timestampLast" : "timestamp_last",
               "_weight" : "weight",
        ]
    }
}
