//
//  Routines.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Routines: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _routineName: String?
    var _exerciseList: [String]?
    var _repList: [String]?
    var _weightList: [String]?
    
    class func dynamoDBTableName() -> String {

        return "slink-mobilehub-286091421-Routines"
    }
    
    class func hashKeyAttribute() -> String {

        return "_routineName"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_routineName" : "routineName",
               "_exerciseList" : "exerciseList",
               "_repList" : "repList",
               "_weightList" : "weightList",
        ]
    }
}
